### PR TITLE
Feature/add ev markers

### PR DESCRIPTION
**Pull request by JonHarrison**
Add EV location markers to Google map

### CODE REVIEW

**Review by agaffar74 — COMMENTED** [review]
Looks all ok to me

**Review by agaffar74 — COMMENTED** [review]
Great job!

**Review by agaffar74 — COMMENTED** [review]
Looks ok to me.

**Comment by umaparu** [comment]
looks good for me.

**Review by umaparu — APPROVED** [review]
looks good for me

**Pull request merged**
